org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=false

# Project
version=2026.6.0
group=com.github.epsilon

# Common
mod_id=epsilon
mod_name=Epsilon
mod_author=Chen_Meng, ilove0329P
license=Apache License 2.0
credits=
description=A powerful cheat mod for Minecraft
