[versions]
project-java = "25"
project-minecraft = "26.2"
project-minecraft-range = "[26.2]"
project-neoform = "26.2-2"
project-fabric-api = "0.156.0+26.2"
project-fabric-loader = "0.19.3"
project-neoforge = "26.2.0.76"
project-neoforge-loader-range = "[4,)"
fabric-loom = "1.15.5"
neoforged-moddev = "2.0.140"
buildconfig = "6.0.9"
foojay-resolver-convention = "1.0.0"
mixin = "0.8.5"
mixinextras = "0.5.4"
asm = "9.8"
sodium-fabric = "mc26.2-0.9.1-fabric"
sodium-neoforge = "mc26.2-0.9.1-neoforge"
iris-fabric = "1.11.2+26.2-fabric"
iris-neoforge = "1.11.2+26.2-neoforge"

[libraries]
minecraft = { module = "com.mojang:minecraft", version.ref = "project-minecraft" }
fabric-loader = { module = "net.fabricmc:fabric-loader", version.ref = "project-fabric-loader" }
fabric-api = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "project-fabric-api" }
mixin = { module = "org.spongepowered:mixin", version.ref = "mixin" }
mixinextras-common = { module = "io.github.llamalad7:mixinextras-common", version.ref = "mixinextras" }
asm = { module = "org.ow2.asm:asm", version.ref = "asm" }
sodium-fabric = { module = "maven.modrinth:sodium", version.ref = "sodium-fabric" }
sodium-neoforge = { module = "maven.modrinth:sodium", version.ref = "sodium-neoforge" }
iris-fabric = { module = "maven.modrinth:iris", version.ref = "iris-fabric" }
iris-neoforge = { module = "maven.modrinth:iris", version.ref = "iris-neoforge" }

[plugins]
fabric-loom = { id = "net.fabricmc.fabric-loom", version.ref = "fabric-loom" }
neoforged-moddev = { id = "net.neoforged.moddev", version.ref = "neoforged-moddev" }
buildconfig = { id = "com.github.gmazzo.buildconfig", version.ref = "buildconfig" }
foojay-resolver-convention = { id = "org.gradle.toolchains.foojay-resolver-convention", version.ref = "foojay-resolver-convention" }
